language: c
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "fzfUOD04wQIJ9Q/YRohizoT1Nqx7PzcLq6ART/ohtfhqlXJ9d2L+4vO2mUuzH7e6XXrxeV/7Zckvb6GcGN6xAZiEuVQylDhWZ22zN80h2oyRLBIRwF2/j/qmwj54Egp3d6/OCvRNHuU4HG00WOFCwRZum+UgZYSM9nLaWE8Mlkk="
addons:
  coverity_scan:
    project:
      name: "ThomasAdam/mvwm"
      description: "mvwm - fvwm cleanup project"
    notification_email: thomas.adam22@gmail.com
    build_command_prepend: "sudo apt-get update -qq && sudo apt-get -y install debhelper autotools-dev dh-autoreconf file fontconfig gettext libfontconfig-dev libfreetype6-dev libfribidi-dev libncurses5-dev libreadline-dev libpng-dev libsm-dev libx11-dev libxcursor-dev libxext-dev libxft-dev libxi-dev libxrandr-dev libxpm-dev libxrender-dev libxt-dev sharutils xsltproc build-essential && ./autogen.sh"
    build_command: "make && make distcheck2"
    branch_pattern: coverity_scan
matrix:
    include:
        - compiler: gcc
          env: CFLAGS="-g -O2 -Wall -Wpointer-arith -fno-strict-aliasing -Werror"
        - compiler: clang
          env: CFLAGS="-g -O2"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install debhelper autotools-dev dh-autoreconf file fontconfig gettext libfontconfig-dev libfreetype6-dev libfribidi-dev libncurses5-dev libreadline-dev libpng-dev libsm-dev libx11-dev libxcursor-dev libxext-dev libxft-dev libxi-dev libxrandr-dev libxpm-dev libxrender-dev libxt-dev sharutils xsltproc build-essential
script: (CFLAGS= ./autogen.sh) && make && make distcheck2 
