language: c
matrix:
    include:
        - compiler: gcc
          env: CFLAGS="-g -O2 -Wall -Wpointer-arith -fno-strict-aliasing -Werror"
        - compiler: clang
          env: CFLAGS="-g -O2"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install debhelper autotools-dev dh-autoreconf file fontconfig gettext libfontconfig-dev libfreetype6-dev libfribidi-dev libncurses5-dev libreadline-dev libpng-dev libsm-dev libx11-dev libxcursor-dev libxext-dev libxft-dev libxi-dev libxrandr-dev libxpm-dev libxrender-dev libxt-dev sharutils xsltproc build-essential
script: (CFLAGS= ./autogen.sh) && make && make distcheck2 
